// Generated by gencpp from file hello_service_server_client/AddInts.msg
// DO NOT EDIT!


#ifndef HELLO_SERVICE_SERVER_CLIENT_MESSAGE_ADDINTS_H
#define HELLO_SERVICE_SERVER_CLIENT_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <hello_service_server_client/AddIntsRequest.h>
#include <hello_service_server_client/AddIntsResponse.h>


namespace hello_service_server_client
{

struct AddInts
{

typedef AddIntsRequest Request;
typedef AddIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInts
} // namespace hello_service_server_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hello_service_server_client::AddInts > {
  static const char* value()
  {
    return "f0b6d69ea10b0cf210cb349d58d59e8f";
  }

  static const char* value(const ::hello_service_server_client::AddInts&) { return value(); }
};

template<>
struct DataType< ::hello_service_server_client::AddInts > {
  static const char* value()
  {
    return "hello_service_server_client/AddInts";
  }

  static const char* value(const ::hello_service_server_client::AddInts&) { return value(); }
};


// service_traits::MD5Sum< ::hello_service_server_client::AddIntsRequest> should match
// service_traits::MD5Sum< ::hello_service_server_client::AddInts >
template<>
struct MD5Sum< ::hello_service_server_client::AddIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hello_service_server_client::AddInts >::value();
  }
  static const char* value(const ::hello_service_server_client::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_service_server_client::AddIntsRequest> should match
// service_traits::DataType< ::hello_service_server_client::AddInts >
template<>
struct DataType< ::hello_service_server_client::AddIntsRequest>
{
  static const char* value()
  {
    return DataType< ::hello_service_server_client::AddInts >::value();
  }
  static const char* value(const ::hello_service_server_client::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hello_service_server_client::AddIntsResponse> should match
// service_traits::MD5Sum< ::hello_service_server_client::AddInts >
template<>
struct MD5Sum< ::hello_service_server_client::AddIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hello_service_server_client::AddInts >::value();
  }
  static const char* value(const ::hello_service_server_client::AddIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hello_service_server_client::AddIntsResponse> should match
// service_traits::DataType< ::hello_service_server_client::AddInts >
template<>
struct DataType< ::hello_service_server_client::AddIntsResponse>
{
  static const char* value()
  {
    return DataType< ::hello_service_server_client::AddInts >::value();
  }
  static const char* value(const ::hello_service_server_client::AddIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HELLO_SERVICE_SERVER_CLIENT_MESSAGE_ADDINTS_H
